order_final_traits <- c(
  "scz2022",
  "bip2021",
  "mdd2019",
  "adhd2023",
  "problematic_alcohol_use2023",
  "educational_attainment",
  "iq",
  "neuroticism",
  "insomnia",
  "suicide_attempt",
  "suicide_death",
  "alcohol_drinks_per_week",
  "smoking_cigarettes_per_day",
  "smoking_initiation",
  "alzheimers_disease",
  "parkinson2019",
  "stroke",
  "amyotrophic_lateral_sclerosis",
  "multiple_sclerosis",
  "epilepsy",
  "migraine",
  "hearing_loss",
  "cortical_surface_area",
  "cortical_thickness",
  "volume_accumbens",
  "volume_amygdala",
  "volume_brainstem",
  "volume_caudate",
  "volume_pallidum",
  "volume_putamen",
  "volume_thalamus",
  "height",
  "bmi",
  "cbc_hematocrit",
  "cbc_lymphocyte",
  "cbc_neutrophil"
)

order_ct <- c(
  "Upper-layer intratelencephalic",
  "Deep-layer intratelencephalic",
  "Deep-layer near-projecting",
  "Deep-layer corticothalamic and 6b",
  "Hippocampal CA1-3",
  "Hippocampal CA4",
  "Hippocampal dentate gyrus",
  "Amygdala excitatory",
  "Thalamic excitatory",
  "MGE interneuron",
  "CGE interneuron",
  "LAMP5-LHX6 and Chandelier",
  "Medium spiny neuron",
  "Eccentric medium spiny neuron",
  "Splatter",
  "Midbrain-derived inhibitory",
  "Mammillary body",
  "Lower rhombic lip",
  "Upper rhombic lip",
  "Cerebellar inhibitory",
  "Miscellaneous",
  "Astrocyte",
  "Bergmann glia",
  "Choroid plexus",
  "Committed oligodendrocyte precursor",
  "Ependymal",
  "Fibroblast",
  "Microglia",
  "Oligodendrocyte precursor",
  "Oligodendrocyte",
  "Vascular"
)

# for conditional analysis plot:
order_ct2 <- c("Upper-layer intratelencephalic",
              "Deep-layer intratelencephalic",
              "Deep-layer corticothalamic and 6b",
              "Hippocampal CA1-3",
              "Hippocampal CA4",
              "Hippocampal dentate gyrus",
              "Amygdala excitatory",
              "Thalamic excitatory",
              "MGE interneuron",
              "CGE interneuron",
              "LAMP5-LHX6 and Chandelier",
              "Medium spiny neuron",
              "Eccentric medium spiny neuron",
              "Cerebellar inhibitory",
              "Miscellaneous"
)

order_traits_mdd = c(
  "mdd2019 (170.8k)",
  "bip2021_type1 (25.1k)",
  "bip2021_type2 (6.8k)",
  "single_episode (21k)",
  "recurrent (30.2k)",
  "mild_impair (28.7k)",
  "moderate_impair (29k)",
  "severe_impair (25.8k)",
  "without_suicidal_thought (37.1k)",
  "with_suicidal_thought (41k)",
  "mdd_ppd (17.3k)",
  "atypical (2.9k)",
  "non-atypical (46.9k)",
  "mild (11.3k)",
  "severe (7.9k)",
  "no_comorbid-anxiety (16.5k)",
  "comorbid_anxiety (24.5k)",
  "early_onset (29.3k)",
  "late_onset (27.8k)",
  "mdd_ect (2.7k)"
)

order_traits_mdd2=c(
  "mdd2019 (170.8k)",
  "bip2021_type1 (25.1k)",
  "bip2021_type2 (6.8k)",
  "severe_impair (25.8k)",
  "moderate_impair (29k)",
  "mild_impair (28.7k)",
  "recurrent (30.2k)",
  "single_episode (21k)",
  "with_suicidal_thought (41k)",
  "without_suicidal_thought (37.1k)",
  "mdd_ppd (17.3k)"
)

#- for 4a heatmap:
order_regions <- c(
  "FrCx",
  "LimCx",
  "ParCx",
  "TempCx",
  "OccCx",
  "PalCx",
  "HC",
  "Amyg",
  "BasFB",
  "Thal",
  "HTH",
  "CBL",
  "MidB",
  "Pons",
  "Medul",
  "SC"
)
# order of cell types (Superclusters), short name
order_ct3 <- c("UL-IT",
              "DL-IT",
              "DL-NP",
              "DL-CT",
              "CA1-3",
              "CA4",
              "HiDG",
              "AmygExc",
              "ThalExc",
              "MGE-IN",
              "CGE-IN",
              "LLC-IN",
              "MSN",
              "eMSN",
              "Splatter",
              "MBIn",
              "Mam",
              "L RombLip",
              "U RombLip",
              "CerIn",
              "Misc",
              "Astr",
              "B",
              "CPlx",
              "COP",
              "Epend",
              "Fibr",
              "MiG",
              "OPC",
              "Olig",
              "Vasc")

#- for 4b
order_regions2 <- c("Frontal_cortex",
                    "Limbic_cortex",
                    "Parietal_cortex",
                    "Temporal_cortex",
                    "Occipital_cortex",
                    "Paleo_cortex",
                    "Hippocampus",
                    "Amygdala",
                    "BasalForebrain",
                    "Thalamus",
                    "HTH",
                    "Cerebellum",
                    "Midbrain",
                    "Pons",
                    "Medulla",
                    "SpinalCord")
order_regions2 <- gsub("_", "\n", order_regions2)